### ISSUE TITLE
Your ReadMe and Wiki Docs Still Lack Clarity, Help Appreciated

### ISSUE THREAD

**Issue by ghost** [diablodale/jit.openni#24]
Hi - everything you do is amazing and I'd like to express gratitude for that in the foreground of this complaint.

That said: can you please expand in your documentation what these instructions mean: 

Additional Mac OSx install notes:

expand, run, and install the libusb-1.0.9 package
expand OpenNI and in that folder sudo ./install.sh
expand NITE and in that folder sudo ./install.sh
expand SensorKinect and in that folder sudo ./install.sh

i.e. What does "sudo ./install.sh" even mean? Do I need to open something in Terminal? Could you indicate what that is and the appropriate steps? Literally "Open Terminal" etc...?

If understanding this section requires external knowledge perhaps you could indicate that somewhere? Or include a link along the lines of "Sudo for Dummies" or "Sudo for Pseudo-Programmers" ? I can follow explicit instructions if they are provided but I really feel something is missing here because double-clicking install.sh takes me to Unitron and nothing happens. 

I know you are a genius but a lot of us are not and just want to play with Kinects and Max and make silly noises. 

Thanks a ton for your time.

CG

**Comment by mindymosher** [comment]
I don't know if you ever got an answer to this, but other people might want to know as well so I'm going to try to clarify (I once was also mystified by sudo and such).

sudo (all lowercase when typed into a terminal window) is short for (s)uper (u)ser (do) as in to execute an action. It is a unix program (macintosh computers have an operating system that is based off of unix) that allows you to do things as the "superuser" or "root" login of the machine. Inside of iOS, this is similar to when you install something and it asks you to provide an administrator password-- basically some things need absolute highest permission in order to install, remove, or whatever they are attempting to do.

install.sh is a "shell" script.  A "shell" in unix is a command line (read: text based, usually in a terminal) interface to the operating system of a computer. Utilizing a shell allows you to make changes to your computer with text commands. In this case, this shell script is essentially a text file full of shell commands that handle the installation of the program so that you don't have to type them in manually.

When you type:

sudo install.sh

into a terminal window (I broke it onto a separate line so that the text would stand alone, otherwise I'd have to use quotations and that is confusing, because you wouldn't know whether or not to include the quotations when attempting this in a terminal.) it is saying "As a super user, run the install.sh script."

This will allow you to install everything that you need to install, and if you install the files he mentions in the wiki file, you will be able to utilize a kinect within Max.  

I hope this helps you (though it might be too late, it says you wrote this 10 months ago), and others who may not be familiar with installing things via terminal!

**Comment by gouvrit** [comment]
hi
thanks for your explanation. The guy that asked the question, might be gone by now, but it stays for people still trying to get this to work after everybody else moved on.

There is still one confusing step.
In the original post from github (https://github.com/diablodale/jit.openni/wiki) where it says: 
- expand OpenNI and in that folder sudo ./install.sh
- expand NITE and in that folder sudo ./install.sh
- expand SensorKinect and in that folder sudo ./install.sh

If you open the extracted folder, yes there is a "install.sh" file. But how do you run the terminal into that file? Do you open a terminal, drag the file so it opens that location in the terminal then write sudo ./install.sh? then drag the  "install.sh" file from the next folder and write again sudo ./install.sh? 

I did that, but since NITE (second step) doesn't exist anymore, I don't know if the window dragging worked. Can anyone confirm if that's the way?

thanks

**Comment by diablodale** [comment]
As @mindymosher wrote about, you type it all.
type "sudo...."
There is no drag drop.
http://www.maclife.com/article/feature/25_terminal_tips_every_mac_user_should_know
http://mac.appstorm.net/how-to/utilities-how-to/how-to-use-terminal-the-basics/

Apple purchase and then killed OpenNI. It is dead.
Please be aware. NITE is illegal to retain, use, or distribute.
