### ISSUE TITLE
Unexpected "jit_openni: XMLconfig initialization failed" error

### ISSUE THREAD

**Issue by imklif** [diablodale/jit.openni#29]
Hi Dale,

I didn't start my Kinect patches for few months and now I keep getting following errors in Max window when I try to read the config file:

jit_openni: XMLconfig initialization failed (One or more of the following nodes could not be enumerated:)
jit_openni: XML config initialization open failed (Can't create any node of the requested type!)

Max 6.1.6. (but i get the same results with 6.0.5 and 6.0.8)
OSX 10.8.5

It worked before. I tried old jit.freenect.grab to see if something is wrong with Kinect sensor, but it still works fine.

Klif

**Comment by diablodale** [comment]
Its unlikely a code defect with jit.openni since that hasn't changed or been re/un-installed. Its likely something external to it.

OpenNI and Mac are notoriously unstable together. Unfortunately, there is not enough information to provide you any advice beyond what OpenNI is telling you via the error messages.

Perhaps try uninstalling it all and reinstalling. I've heard that the Mac can't uninstall the libusb part but the other two (openni and nite) have uninstallers built into them.

Or maybe your config file is invalid/corrupt. USB port is wonky. OsX was changed and now OpenNI doesn't support it. etc.

**Comment by imklif** [comment]
Hi Dale,

Thank you for your prompt reply!

Reinstaling the drivers fixed the issues :)

Klif
