### ISSUE TITLE
getting nan

### ISSUE THREAD

**Issue by Vllrich** [diablodale/jit.openni#8]
Thanks for this amazing work!

I'm getting nan @ l_collar, r_collar, waist, wrist

OSX 10.8.2, MaxMSP 6.08

Salut!

**Comment by diablodale** [comment]
This is by design. NITE does not currently support and track all the joints that OpenNI defines. Therefore, null values are returned in those cases.
You will find several joints are not supported by the current NITE driver (collar, waist, wrist, fingertip, and ankle).
When PrimeSense releases a newer NITE build that supports these joints, then jit.openni will automatically start returning meaningful values for them.

Does this resolve your inquiry?

**Comment by Vllrich** [comment]
Ok, thanks a lot!
